Allow bad unicode encoding in __repr__
Pypy returns the following strange encoding error sometimes:

    ======================================================================
    FAIL: test_unicode_handling
    (tests.richenum.test_ordered_rich_enums.OrderedRichEnumTestSuite)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/samv/projects/richenum/tests/richenum/test_ordered_rich_enums.py", line 120, in test_unicode_handling
        r"<BreakfastEnumValue #3: oatmeal. \('Oatmeal.'\)>",
    AssertionError: Regexp didn't match: "<BreakfastEnumValue #3: oatmeal. \\('Oatmeal.'\\)>" not found in "<BreakfastEnumValue #3: oatmeal??
    ('Oatmeal??')>"

    ======================================================================
    FAIL: test_unicode_handling
    (tests.richenum.test_rich_enums.RichEnumTestSuite)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/samv/projects/richenum/tests/richenum/test_rich_enums.py", line 145, in test_unicode_handling
        "<VegetableEnumValue: okra. \('Okra.'\)>",
    AssertionError: Regexp didn't match: "<VegetableEnumValue: okra. \\('Okra.'\\)>" not found in "<VegetableEnumValue: okra?? ('Okra??')>"

    ----------------------------------------------------------------------
    Ran 34 tests in 0.047s

    FAILED (failures=2)

Somehow this multi-byte character is getting converted to two ??'s.  It
happens occasionally locally, but not repeatably.  It doesn't matter
hugely, as it is mostly costmetic: let it stand.